### ISSUE TITLE
Python3.6 compatability

### ISSUE THREAD

**Issue by dobrynski** [doubleO8/enigma2_http_api#3] opened 2018-07-09 13:11 UTC
Thanks for a great API library that I have found very useful.

I'm looking forward to creating a component for Home Assistant using this library, but Python 3.6 compatibility is holding me back. Is there any chance that you could make this library Python3.6 compatible? A lot of the work can be done by just running 2to3 on it.

Thanks in advance regardless.

**Comment by doubleO8** [comment] 2018-07-16 11:49
duplicate of #1

**Closed as completed by doubleO8** 2018-07-16 11:49 UTC

**Comment by dobrynski** [comment] 2018-08-13 11:59
Sorry for that I had forgotten that I had already brought this up once before. Interestingly my enigma2 based device also has python3.5 on it.

If I can't figure out how to make a python2/3 compatible version, would you mind if I created a cut-down python3 version under a different name and credited you?
